// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACghbER1FdaFKona9cwENsIqI9UGDqSVg',
    appId: '1:390505621519:android:dc7f8294999eebbc879b7a',
    messagingSenderId: '390505621519',
    projectId: 'insurance-process-controle',
    storageBucket: 'insurance-process-controle.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA32bkQUIEfDb70rbq-EnZUIfR3iUwWcY',
    appId: '1:390505621519:ios:a26f2583e5a53ca4879b7a',
    messagingSenderId: '390505621519',
    projectId: 'insurance-process-controle',
    storageBucket: 'insurance-process-controle.firebasestorage.app',
    iosBundleId: 'com.example.iPc',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA32bkQUIEfDb70rbq-EnZUIfR3iUwWcY',
    appId: '1:390505621519:ios:a26f2583e5a53ca4879b7a',
    messagingSenderId: '390505621519',
    projectId: 'insurance-process-controle',
    storageBucket: 'insurance-process-controle.firebasestorage.app',
    iosBundleId: 'com.example.iPc',
  );
}
